 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.6.4
     steps: 
       - checkout
       - run: sudo pip install pipenv
       - run: pipenv install
       - run: pipenv run pytest test_sample.py
       - run: echo "hello"
