 version: 2
 jobs:
   one:
     docker:
       - image: quoinedev/python3.6-pandas-alpine
     steps:
       - checkout
       - run: echo "A first hello 2"
       - run: sleep 3
   two:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A more familiar hi"
       - run: sleep 5
       - run: echo "A more familiar hi2"
 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
